package c4

import org.scalacheck.{Gen, Properties}
import org.scalacheck.Prop.forAll
import C4Array.Ops

class C4ArraySpec extends Properties("C4Array.Ops") {
  // TODO - could add more checks here - this is enough for a prototype
  // Should also check how it handles errors generated by f
  property("mapC4 == regular map") = forAll { array: Array[Int] =>
    array.map(_ * 2).sameElements(array.mapC4(_ * 2))
  }

  property("filterC4 == regular filter") = forAll { array: Array[Int] =>
    array.filter(_ > 10).sameElements(array.filterC4(_ > 10))
  }
}