package c4

import org.scalacheck.Properties
import org.scalacheck.Prop.forAll
import C4ParUtils.C4ExecutionContext
import Fuse.Ops

class FuseProp extends Properties("FuseProp") {
  implicit val ec: C4ExecutionContext = C4ExecutionContext(parallelism = 4)

  // TODO - could add more checks here - this is enough for a prototype
  // Should also check how it handles errors generated by f
  property("fuse.map.boom == regular map") = forAll { array: Array[Int] =>
    array.map(_ * 2).sameElements(array.fuse.map(_ * 2).boom)
  }

  property("fuse.map.parBoom == regular map") = forAll { array: Array[Int] =>
    array.map(_ * 2).sameElements(array.fuse.map(_ * 2).parBoom)
  }

  property("fuse.filter.boom == regular filter") = forAll { array: Array[Int] =>
    array.filter(_ > 10).sameElements(array.fuse.filter(_ > 10).boom)
  }

  property("fuse.filter.parBoom == regular filter") = forAll { array: Array[Int] =>
    array.filter(_ > 10).sameElements(array.fuse.filter(_ > 10).parBoom)
  }

  property("fuse.map.filter.map.boom == regular map.filter.map") = forAll { array: Array[Int] =>
    array.map(_ * 5).filter(_ > 10).map(_ / 2).sameElements(
      array.fuse.map(_ * 5).filter(_ > 10).map(_ / 2).boom
    )
  }

  property("fuse.map.filter.map.parBoom == regular map.filter.map") = forAll { array: Array[Int] =>
    array.map(_ * 5).filter(_ > 10).map(_ / 2).sameElements(
      array.fuse.map(_ * 5).filter(_ > 10).map(_ / 2).parBoom
    )
  }
}
